server:
  port: 8080
  error:
    include-message: always

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    username: services_quality_monitoring
    password: password
    url: jdbc:postgresql://postgres:5435/services_quality_monitoring
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://postgres:5435/services_quality_monitoring
    user: services_quality_monitoring
    password: password
